package jyotish.analyze.bhavas.bhava1.lagna.ascendant;

public class LeoAscendant {
	
    public enum FUNCTIONAL_MALEFIC{LAGNA,SURYA,CHANDRA,MANGAL,BUDHA,GURU,SHUKRA,SHANI,RAHU,KETU};
	
    public enum FUNCTIONAL_BENEFIC{LAGNA,SURYA,CHANDRA,MANGAL,BUDHA,GURU,SHUKRA,SHANI,RAHU,KETU};
	
	public enum FUNCTIONAL_NUETRAL{LAGNA,SURYA,CHANDRA,MANGAL,BUDHA,GURU,SHUKRA,SHANI,RAHU,KETU};

}
