package dattatreya.jyotish.util;

public enum Jyotirlingams {
	
	RAMESHWARAM,SOMNATH,NAGESHWAR,OMKARESHWAR,DHUSANESHWAR,MALIKARJUNA,MAHAKALA,VAIDYANATH,VISHWANATH,BHIMASHANKARA,KEDARNATH,TRIMBAKESHWAR

}
