package dattatreya.jyotish.util;

public enum Mahavidya {
	MATANGI, BHUVANESHWARI, BAGALAMUKHI, TRIPURASUNDARI, UGRATARA_NEELATARA, KAMALATMIKA, DAKSHINAKALI, CHINNAMASTA, DHOOMAVATI, BHAIRAVI
}
