package dattatreya.jyotish.util;

public enum NakshtraDiety {
	ASHWINI_KUMARS, YAMA, AGNI, BRAHMA, SOMA, SHIVA, ADITI, BRIHASPATI, NAGA, PITRI, PUSHAA, BHAGA, SURYA, TWASTA, VAYU, INDRAGNI, MITRADEVA, INDRA, AAP, VISHWADEVA, VISHNU, ASTA_VASU, AJANMAA, AHIR_BUDHNYA, PUSHA
}