package dattatreya.jyotish.util;

public class NakshatraEnumUtil {

	public enum NAME_OF_NAKSHTRA {
		ASHWINI(1), BHARANI(2), KRITTIKA(3), ROHINI(4), MRIGASHIRSHA(5), ARUDRA(6), PUNARVASU(7), PUSHYA(8), ASHLESHA(
				9), MAGHA(10), PURVA_PHALGUNI(11), UTTAR_PHALGUNI(12), HASTA(13), CHITRA(14), SWATI(
						15), VISHAKA(16), ANURADHA(17), JYESTHA(18), MULA(19), PURVA_ASHADA(20), UTTAR_ASHADA(
								21), SHRAVANA(22), DHANISHTA(
										23), SATABHISHA(24), PURVA_BHADRAPADA(25), UTTAR_BHADRAPADA(26), REVATI(27);

		private final int i;

		private NAME_OF_NAKSHTRA(int i) {
			this.i = i;
		}

		public int getNumber() {
			return i;
		}
	}
	
	public enum NAKSHTRA_GANA {

		DEVA,MANUSHYA,RAKSHASHA
	}
	
	public enum NAKSHATRA_DIETY {
		ASHWINI_KUMARS, YAMA, AGNI, BRAHMA, SOMA, SHIVA, ADITI, BRIHASPATI, NAGA, PITRI, PUSHAA, BHAGA, SURYA, TWASTA, VAYU, INDRAGNI, MITRADEVA, INDRA, AAP, VISHWADEVA, VISHNU, ASTA_VASU, AJANMAA, AHIR_BUDHNYA, PUSHA
	}
	
	public enum NAKSHTRA_TYPE {
		KSHIPRA, UGRA, MISHRA, STHIRA, MRUDU, TIKSHNA, CHARA
	}

	
}
