package dattatreya.jyotish.util;

public enum TithiNames {
	
	PRATIPADA, DWITIYA, TRITIYA, CHATURTHI, PANCHAMI, SHASHTI, SAPTAMI, ASHTAMI, NAVAMI, DASAMI, EKADASHI, DWADASHI, TRAYODASHI, CHATURDASHI, PURNIMA, AMAVASYA

}
