package dattatreya.jyotish.util;

public enum Trees {
	PTEROCARPUS_SANTALINUS, ALSTONIA_SCOLARIS, WRIGHTIA_TINCTORIA, BUTIA_MONOSPERMA, ZIZIPHUS_MAURITIANA, MANGIFERA_INDICA, MIMUSOPS_ELENGI, ACACIA_CATECHU, FICUS_RELIGIOSA, DALBERGIA_SISSOO, PROSOPIS_CINERARIA, FICUS_BENGALENSIS
}