package dattatreya.jyotish.util;

public enum YogaNames {
	
	VISHAKUMBHA,PREETI,AAYUSHMAN,SAUBHAGYA,SHOBHANA,ATIGANDA,SUKARMA,DHRITI,SHOOLA,GAND,VRIDDHI,DHRUVA,VYAGHAATA,HARSHANA,VAJRA,SIDDHI,VYATIPAATA,VARIYAANA,PARIGHA,SHIVA,SIDDHA,SADDHYA,SHUBHA,SHUKLA,BRAHMA,INDRA,VAIDHRITI

}
